apiVersion: v1
kind: Service
metadata:
  name: harborops
  labels:
    app: harborops
spec:
  type: LoadBalancer
  selector:
    app: harborops
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
